import { LABEL, PROJECT_CODE } from "@/lib/brand";
export default function Privacy() {
  return (
    <>
      <h1>Privacy Policy</h1>
      <p className="sub">Proactive {LABEL} QuickBooks Connector ({PROJECT_CODE}) · Last updated September 2026</p>

      <h2>Who we are</h2>
      <p>
        Proactive Supply Chain Group operates this application for its own internal use. It is not
        offered to the public and has no external customers. Contact:{" "}
        <a href="mailto:michael@proactivegroup.ca">michael@proactivegroup.ca</a>.
      </p>

      <h2>What data we access</h2>
      <p>
        With the authorisation of a QuickBooks administrator, the application reads the following
        from Proactive&rsquo;s own QuickBooks Online company files: vendor records (including
        currency), bills and their line detail, document numbers, memo fields, the chart of
        accounts, sales tax codes and rates, and exchange rates. It does not read employee,
        payroll or banking data. What it can write back is described below.
      </p>

      <h2>What we store</h2>
      <p>
        OAuth access and refresh tokens, encrypted with AES-256-GCM before storage; reconciliation
        results and exception decisions generated by Proactive staff; a record of each bill created
        through the application (vendor, number, date, amount, accounts, source document, who
        posted it); and an audit log recording which user performed which action and when. Data is held in a managed PostgreSQL database
        hosted in Canada (ca-central-1).
      </p>

      <h2>What we write back</h2>
      <p>
        On a company file where an administrator has explicitly enabled it, and only for the
        operations the administrator has enabled, the application can:
      </p>
      <ul>
        <li>
          <strong>Set two fields on an existing bill</strong> &mdash; the document number and the
          memo &mdash; to record a carrier&rsquo;s invoice number against the bill it belongs to.
        </li>
        <li>
          <strong>Create a vendor bill</strong> from a supplier invoice that has already been
          approved for payment. A Proactive accounting user reads the invoice, confirms the vendor,
          amounts, tax and the general-ledger account for every line in chat, and gives an explicit
          instruction to post. The application refuses a bill whose vendor and invoice number
          already exist, flags a same-vendor same-amount bill within seven days, and checks that
          lines plus tax equal the invoice total before creating anything.
        </li>
      </ul>
      <p>
        Each change is made one record at a time, is confirmed by a person beforehand, and is
        logged with the full content written. The application cannot delete or void a record,
        cannot change an existing bill&rsquo;s amount, vendor or account, and cannot initiate a
        payment of any kind.
      </p>

      <h2>What we do not do</h2>
      <ul>
        <li>We do not sell, rent, share or disclose QuickBooks data to any third party.</li>
        <li>We do not use QuickBooks data for advertising, profiling or model training.</li>
        <li>
          We do not write to any company file for which writes have not been explicitly enabled
          by an administrator.
        </li>
        <li>We do not process payments and hold no banking credentials.</li>
      </ul>

      <h2>Access control</h2>
      <p>
        Each user signs in with an individual email and password issued by Proactive, optionally
        with an authenticator-app code; passwords are stored only as salted scrypt hashes and
        session tokens only as SHA-256 hashes. Accounts lock after repeated failed attempts, are
        revocable individually, and are withdrawn when a person changes role or leaves.
        Encryption keys are held in the hosting environment&rsquo;s secret store and never in
        source code or the database.
      </p>

      <h2>Retention and deletion</h2>
      <p>
        Tokens are deleted when a company file is disconnected. Audit and reconciliation records
        are retained for seven years as accounting records, consistent with Canadian record-keeping
        requirements. To request deletion of data held by this application, contact the address
        above.
      </p>

      <h2>Disconnecting</h2>
      <p>
        A QuickBooks administrator can revoke this application&rsquo;s access at any time from
        QuickBooks Online under Apps, without notice to us. See{" "}
        <a href="/disconnect">disconnecting a company file</a>.
      </p>

      <h2>Breach notification</h2>
      <p>
        In the event of a security incident affecting QuickBooks data, Proactive will notify
        affected parties and Intuit without undue delay, and in any case within 72 hours of
        becoming aware.
      </p>
    </>
  );
}
